### ISSUE TITLE
Problems with MDB in the mnist example

### ISSUE THREAD

**Issue by moegitree** [BVLC/caffe#1298]
When I tried to do the dataset praparation in Mnist example and execute " ./examples/mnist/create_mnist.sh ", it turns out some failures like this: 

Creating lmdb...
F1016 14:22:01.290793  9722 convert_mnist_data.cpp:132] Check failed: mdb_put(mdb_txn, mdb_dbi, &mdb_key, &mdb_data, 0) == 0 (-30792 vs. 0) mdb_put failed
**\* Check failure stack trace: ***
Aborted (core dumped)
F1016 14:22:01.431432  9724 convert_mnist_data.cpp:132] Check failed: mdb_put(mdb_txn, mdb_dbi, &mdb_key, &mdb_data, 0) == 0 (-30792 vs. 0) mdb_put failed
**\* Check failure stack trace: ***
Aborted (core dumped)
Done.

How can I fix this problem? 
thanks

**Comment by danielhers** [comment]
I am also using Ubuntu 32 bit and got this error. Changing the `1099511627776` to `1073741824` in `examples/mnist/convert_mnist_data.cpp` fixed it.

**Comment by jeremyfix** [comment]
Same issue fixed with your modification of the mnist script on my Ubuntu 32 bits, 14.04 ;

**Comment by SaadRiazQazi** [comment]
I have the exact same error and tried the same fix by chaning value to 1gb, but the error is still there and exactly the same. What can be the problem?

**Comment by SaadRiazQazi** [comment]
Exact output:

`Creating lmdb...

F0407 08:02:22.195675 24302 convert_mnist_data.cpp:138] Check failed: mdb_put(mdb_txn, mdb_dbi, &mdb_key, &mdb_data, 0) == 0 (-30792 vs. 0) mdb_put failed

*** Check failure stack trace: ***

    @ 0xb69ae060  (unknown)

    @ 0xb69adf5c  (unknown)

    @ 0xb69adb78  (unknown)

    @ 0xb69aff98  (unknown)

    @     0xa656  convert_dataset()

    @     0x9e80  main

    @ 0xb6706632  (unknown)

Aborted

F0407 08:02:22.427784 24305 convert_mnist_data.cpp:138] Check failed: mdb_put(mdb_txn, mdb_dbi, &mdb_key, &mdb_data, 0) == 0 (-30792 vs. 0) mdb_put failed

*** Check failure stack trace: ***

    @ 0xb69a6060  (unknown)

    @ 0xb69a5f5c  (unknown)

    @ 0xb69a5b78  (unknown)

    @ 0xb69a7f98  (unknown)

    @     0xa656  convert_dataset()

    @     0x9e80  main

    @ 0xb66fe632  (unknown)

Aborted
`

**Comment by SaadRiazQazi** [comment]
Made Caffe again and now it works.

**Comment by lukeyeager** [comment]
My fix at https://github.com/BVLC/caffe/pull/3731 may help avoid these problems in the future.

**Comment by KangolHsu** [comment]
@sguada make again works for me. I don't know why.
